AllCops:
  Exclude:
    - capistrano_sentinel.gemspec
    - lib/capistrano_sentinel/initializers/**/*
    - bin/**/*
    - Guardfile
    - vendor/**/*
    - spec/**/*
    - Gemfile
    - Rakefile

  TargetRubyVersion: 2.3

ClassLength:
  Max: 500

ModuleLength:
  Max: 500

Documentation:
  Enabled: true

Encoding:
  Enabled: false

LineLength:
  Max: 200

AccessModifierIndentation:
  EnforcedStyle: outdent

IfUnlessModifier:
  Enabled: false

CaseIndentation:
  IndentWhenRelativeTo: case
  IndentOneStep: true

MethodLength:
  CountComments: false
  Max: 40

SignalException:
  Enabled: false

ColonMethodCall:
  Enabled: false

AsciiComments:
  Enabled: false

RegexpLiteral:
  Enabled: false

AssignmentInCondition:
  Enabled: false

ParameterLists:
  CountKeywordArgs: false

SingleLineBlockParams:
  Methods:
    - reduce:
      - memo
      - item

Metrics/AbcSize:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/ExtraSpacing:
  Enabled: true

Style/FileName:
  Enabled: false
